blacklist = [".cache", ".codex", ".config", ".local", "Library", "tmp"]
dir_length = 2
sort_order = ["config", "tmux", "zoxide"]

[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "yazi"

[[session]]
name = "notes"
path = "~/notes"
startup_command = "nvim"
