#!/usr/bin/env bash
set -euo pipefail

lock_screen="${HOME}/.config/sway/scripts/lock-screen"

exec swayidle -w \
  before-sleep "pidof swaylock || \"$lock_screen\" --daemonize" \
  timeout 300 'brightnessctl -s set 10' \
  resume 'brightnessctl -r' \
  timeout 330 "pidof swaylock || \"$lock_screen\" --daemonize" \
  timeout 350 'swaymsg "output * power off"' \
  resume 'swaymsg "output * power on"' \
  timeout 3600 'systemctl suspend'

