----------------------------------------------------------------------
-- Module References
----------------------------------------------------------------------
local tabterm = require("tabterm")
local util = require("util")

----------------------------------------------------------------------
-- Public API
----------------------------------------------------------------------
return function(map)
	map("n", "<leader>gg", function()
		tabterm.open("lazygit", { title = "Lazygit", cwd = util.buf_dir() })
	end, { desc = "Lazygit" })
	map("n", "<leader>gf", function()
		util.fzf_with_cwd("git_status", util.vcs_dir)
	end, { desc = "Status" })
	map("n", "<leader>gc", function()
		util.fzf_with_cwd("git_commits", util.vcs_dir)
	end, { desc = "Commits (repo)" })
	map("n", "<leader>gh", function()
		util.fzf_with_cwd("git_bcommits", util.vcs_dir)
	end, { desc = "History (buffer)" })
	map("n", "<leader>gb", function()
		util.fzf_with_cwd("git_blame", util.vcs_dir)
	end, { desc = "Blame" })
	map("n", "<leader>gB", function()
		util.fzf_with_cwd("git_branches", util.vcs_dir)
	end, { desc = "Branches" })
	map("n", "<leader>gS", function()
		util.fzf_with_cwd("git_stash", util.vcs_dir)
	end, { desc = "Stash" })
	map("n", "<leader>gT", function()
		util.fzf_with_cwd("git_tags", util.vcs_dir)
	end, { desc = "Tags" })
	map("n", "<leader>gd", function()
		util.with_vcs_root(function()
			vim.cmd("Git diff")
		end)
	end, { desc = "Diff" })
	map("n", "<leader>gD", function()
		vim.cmd("Git diff -- " .. vim.fn.expand("%:p"))
	end, { desc = "Diff current file" })
	map("n", "<leader>go", MiniDiff.toggle_overlay, { desc = "Diff overlay toggle" })
	map("n", "<leader>gl", function()
		util.with_vcs_root(function()
			vim.cmd("Git log --stat -200")
		end)
	end, { desc = "Log (stat)" })
	map("n", "<leader>gL", function()
		vim.cmd("Git log --stat -200 -- " .. vim.fn.expand("%:p"))
	end, { desc = "Log current file (stat)" })
	map("n", "<leader>gi", function()
		util.with_vcs_root(function()
			MiniGit.show_at_cursor()
		end)
	end, { desc = "Inspect at cursor" })
	map("n", "<leader>gt", function()
		tabterm.open("tuicr", { title = "Code Review", cwd = util.vcs_dir() })
	end, { desc = "Code review (tuicr)" })
	map("n", "<leader>gj", function()
		util.with_vcs_root(function()
			vim.cmd("J")
		end)
	end, { desc = "Jujutsu" })
end
