-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--
-- Example:
-- vim.keymap.set("n", "<leader>ww", "<cmd>w<cr>", { desc = "Save" })
