#!/usr/bin/env bash
set -euo pipefail

exec google-chrome-stable \
  --user-data-dir="$HOME/.config/chrome" \
  --remote-debugging-port=9222 \
  --enable-features=UseOzonePlatform \
  --ozone-platform=wayland
