#!/usr/bin/env python3
"""
Generate waybar config based on detected compositor.
This script processes the config.jsonc template and generates the final config.
"""

import json
import re
import subprocess
import sys
import os
from pathlib import Path

CONFIG_DIR = Path.home() / ".config" / "waybar"
TEMPLATE = CONFIG_DIR / "config.template.jsonc"
OUTPUT = CONFIG_DIR / "config.jsonc"


def detect_compositor():
    """Detect which compositor is running."""
    # Check running processes
    try:
        result = subprocess.run(
            ["pgrep", "-x", "Hyprland"],
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            return "hyprland"
    except FileNotFoundError:
        pass

    try:
        result = subprocess.run(
            ["pgrep", "-x", "hyprland"],
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            return "hyprland"
    except FileNotFoundError:
        pass

    try:
        result = subprocess.run(
            ["pgrep", "-x", "niri"],
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            return "niri"
    except FileNotFoundError:
        pass

    # Fallback: check commands
    if subprocess.run(["which", "hyprctl"], capture_output=True).returncode == 0:
        return "hyprland"
    elif subprocess.run(["which", "niri"], capture_output=True).returncode == 0:
        return "niri"

    # Default to hyprland
    return "hyprland"


def process_config(template_path, compositor):
    """Process the template and generate the final config."""
    with open(template_path, "r") as f:
        content = f.read()

    if compositor == "hyprland":
        # Replace placeholders for Hyprland
        content = content.replace('"HYPRLAND_WORKSPACES_PLACEHOLDER"', '"hyprland/workspaces"')
        content = content.replace('"HYPRLAND_SUBMAP_PLACEHOLDER"', '"hyprland/submap"')
        content = content.replace('"HYPRLAND_WINDOW_PLACEHOLDER"', '"hyprland/window"')
    elif compositor == "niri":
        # Replace placeholders for Niri
        content = content.replace('"HYPRLAND_WORKSPACES_PLACEHOLDER"', '"niri/workspaces"')
        content = content.replace('"HYPRLAND_WINDOW_PLACEHOLDER"', '"niri/window"')

        # Remove the submap placeholder line and clean up
        # Remove the line with HYPRLAND_SUBMAP_PLACEHOLDER
        lines = content.split("\n")
        new_lines = []
        i = 0
        while i < len(lines):
            line = lines[i]
            # Check if this line contains the submap placeholder
            if 'HYPRLAND_SUBMAP_PLACEHOLDER' in line:
                # Skip this line
                i += 1
                continue
            # Check if current line is spacer3 and next line is submap placeholder
            if i + 1 < len(lines) and 'custom/spacer3' in line and 'HYPRLAND_SUBMAP_PLACEHOLDER' in lines[i + 1]:
                # Skip both spacer3 and submap placeholder
                i += 2
                continue
            new_lines.append(line)
            i += 1

        content = "\n".join(new_lines)

        # Clean up trailing commas
        content = re.sub(r',\s*\]', ']', content)
        content = re.sub(r',\s*}', '}', content)
        content = re.sub(r',,', ',', content)

    return content


def main():
    compositor = detect_compositor()
    print(f"Detected compositor: {compositor}", file=sys.stderr)

    # Determine template: use config.jsonc if it has placeholders, otherwise use template file
    config_file = CONFIG_DIR / "config.jsonc"
    if config_file.exists():
        with open(config_file, "r") as f:
            content = f.read()
            if "PLACEHOLDER" in content:
                # config.jsonc has placeholders, use it as template
                template_path = config_file
            else:
                # config.jsonc is already processed, use template file
                template_path = TEMPLATE
    else:
        template_path = TEMPLATE
    
    if not template_path.exists():
        print(f"Error: Template not found at {template_path}", file=sys.stderr)
        sys.exit(1)

    processed_content = process_config(template_path, compositor)

    # Add disclaimer at the top
    disclaimer = "// GENERATED FILE - DO NOT EDIT DIRECTLY\n"
    disclaimer += "// This file is automatically generated by gen-config.py\n"
    disclaimer += "// Edit config.template.jsonc instead and run gen-config.py to regenerate\n"
    disclaimer += "// Generated for compositor: " + compositor + "\n\n"
    
    # Prepend disclaimer to content
    processed_content = disclaimer + processed_content

    # Write to output
    with open(OUTPUT, "w") as f:
        f.write(processed_content)

    print(f"Generated waybar config for {compositor}", file=sys.stderr)


if __name__ == "__main__":
    main()
