{:user {:plugins [[jonase/eastwood "0.1.0"]
                  [lein-ancient "0.5.4"]
                  [lein-cljsbuild "0.3.3"]
                  [lein-cloverage "1.0.2"]
                  [lein-kibit "0.0.8"]
                  [lein-release "1.0.5"]
                  [lein-try "0.4.1"]
                  [lein-vanity "0.2.0"]
                  [org.clojars.kurtharriger/lein-depgraph "0.1.0"]
                  [lein-pprint "1.1.1"]]
        :dependencies [[clojure-complete "0.2.3"]
                       [criterium "0.4.3"]
                       [slamhound "1.5.2"]]}}
