[[mgr.prepend_keymap]]
on   = [ "c", "i" ]
run  = "shell '$HOME/.config/yazi/scripts/copy-file-to-clipboard \"$0\"'"
desc = "Copy content to clipboard"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd sftp://bubba/"
desc = "Go to bubba"

[[mgr.prepend_keymap]]
on   = [ "g", "t" ]
run  = "shell 'ya emit cd \"$($HOME/.config/yazi/scripts/open-trash-dir)\"'"
desc = "Go to Trash"

[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = "shell 'glow \"$0\" -p' --block"
desc = "Preview with glow"
