[[mgr.prepend_keymap]]
on   = [ "z" ]
run  = "plugin zoxide"
desc = "Jump to a directory via zoxide"

[[mgr.prepend_keymap]]
on   = [ "Z" ]
run  = "plugin fzf"
desc = "Jump to a file/directory via fzf"

[[mgr.prepend_keymap]]
on   = [ "c", "i" ]
run  = "shell 'clipf \"$0\"'"
desc = "Copy content to clipboard"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd sftp://bubba/"
desc = "Go to bubba"

[[mgr.prepend_keymap]]
on   = [ "g", "t" ]
run  = "shell 'ya emit cd \"$(trashd)\"'"
desc = "Go to Trash"

[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = "shell 'm \"$0\"' --block"
desc = "Preview in pager"
